name: ci

on:
  push:
    branches: 
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lambdastack:20.04

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    -
      name: lowercase actor name
      run: echo "ACTOR_NAME=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Login to GitHub Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: Dockerfile.stub
        tags: ${{ env.REGISTRY }}/${{ env.ACTOR_NAME }}/${{ env.IMAGE_NAME }}
